---
title: "ph1930_hw2_ygu5"
author: "Yue Gu"
date: "9/26/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1 Recursion
```{r}
num_step_ways = function(n){
  if (n == 0 | n == 1 | n == 2)
    return(1)
  else if (n == 3)
    return(2)
  else 
    return(num_step_ways(n-3) + num_step_ways(n-1))
}
# test
num_step_ways(1)
num_step_ways(2)
num_step_ways(3)
num_step_ways(4) # 3 ways: 1+1+1+1, 1+3, 3+1
num_step_ways(7) # 9 ways: 1+1+1+1+1+1+1, 1+3+1+1+1, 1+3+3, 3+1+1+1, 1+1+3+1+1, 1+1+1+3+1, 1+1+1+1+3, 3+1+3, 3+3+1
```

# 2 Function and Environment
```{r}
source("./grader/roman_solution.R")
for (i in 1:3){
  a = roman_trans(roman_trans_input_lt[[i]])
  print(a)
}

source("./grader/student1.R")
for (i in 1:3){
  b = roman_trans(roman_trans_input_lt[[i]])
  print(b)
}
system.time(b)

source("./grader/student4.R")
for (i in 1:3){
  c = roman_trans(roman_trans_input_lt[[i]])
  print(c)
}
system.time(for (i in 1:3){
  c = roman_trans(roman_trans_input_lt[[i]])
  print(c)
})

all.equal(a, c)
c/a

get_authors

# write grader function
setwd("./grader/")

grader = function(){
  if (!require("rstudioapi")) install.packages("rstudioapi")
  library("rstudioapi") 
  
  # set to current Rscript directory
  setwd(dirname(getSourceEditorContext()$path))
  
  source("./roman_solution.R")
  
  for (i in 1:3){
  a = roman_trans(roman_trans_input_lt[[i]])
  }

source("./student1.R")
for (i in 1:3){
  b = roman_trans(roman_trans_input_lt[[i]])
}
y = system.time(for (i in 1:3){
  b = roman_trans(roman_trans_input_lt[[i]])
})
 
  
  
  write.csv("./results.csv")
}

source("student1.R")
author
```

